# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "m4dz"
license = "MIT"
licenselink = "https://github.com/m4dz/m4dz-hugo-theme/blob/master/LICENSE"
description = "m4dz' website custom theme for Hugo static engine"
homepage = "https://github.com/m4dz/m4dz-hugo-theme"
tags = []
features = []
min_version = 0.19

[author]
  name = "m4dz"
  homepage = "https://m4dz.net"
